### ISSUE TITLE
Is there any way to show four cameras at once?

### ISSUE THREAD

**Issue by noho501** [Neos21/multi-cam#1]
I tried but not success. It just works on three cameras but Doubletake app showing four. https://apps.apple.com/vn/app/doubletake-by-filmic-pro/id1478041592

**Comment by Neos21** [comment]
I want to use four cameras too! But I think there is no way.
I saw `supportedMultiCamDeviceSets`, but four cameras option did not exist.

Doubletake does not use telephoto lens.
Doubletake magnifies the standard lens to make it look like a telephoto lens.

**Comment by noho501** [comment]
Thanks for you advice

**Comment by ZG-123** [comment]
> I tried but not success. It just works on three cameras but Doubletake app showing four. https://apps.apple.com/vn/app/doubletake-by-filmic-pro/id1478041592

您好，请问两个摄像头怎么实现呢
